services:
  db:
    container_name: dev_db
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: kotak
    ports:
      - "5432:5432"
    volumes:
      - pg_dev_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d kotak"]
      interval: 5s
      timeout: 5s
      retries: 5

  valkey:
    container_name: dev_valkey
    image: valkey/valkey
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - valkey_dev_data:/data
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pg_dev_data:
  valkey_dev_data:
