services:
  db:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: kotak
    ports:
      - "5432:5432"
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d kotak"]
      interval: 5s
      timeout: 5s
      retries: 5

  migrator:
    image: ghcr.io/pxr05/kotak:latest
    command: ["bun", "run", "db:migrate"]
    environment:
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      - db

  web:
    image: ghcr.io/pxr05/kotak:latest
    command: ["bun", "--bun", "run", "."]
    restart: always
    environment:
      BODY_SIZE_LIMIT: Infinity
      ORIGIN: ${PROTOCOL}://${DOMAIN}
      DATABASE_URL: ${DATABASE_URL}
      LIMITER_SECRET: ${LIMITER_SECRET}
    ports:
      - "4321:3000"
    volumes:
      - ./web_data:/var/lib/localdrive
    depends_on:
      - db

volumes:
  pg_data:
  web_data:
  letsencrypt:
