CREATE INDEX "file_owner_id_idx" ON "file" USING btree ("owner_id");--> statement-breakpoint
CREATE INDEX "file_folder_id_idx" ON "file" USING btree ("folder_id");--> statement-breakpoint
CREATE INDEX "file_owner_id_folder_id_idx" ON "file" USING btree ("owner_id","folder_id");--> statement-breakpoint
CREATE INDEX "file_owner_id_name_idx" ON "file" USING btree ("owner_id","name");--> statement-breakpoint
CREATE INDEX "file_name_idx" ON "file" USING btree ("name");--> statement-breakpoint
CREATE INDEX "file_storage_key_idx" ON "file" USING btree ("storage_key");--> statement-breakpoint
CREATE INDEX "file_share_file_id_idx" ON "file_share" USING btree ("file_id");--> statement-breakpoint
CREATE INDEX "file_share_shared_by_idx" ON "file_share" USING btree ("shared_by");--> statement-breakpoint
CREATE INDEX "file_share_file_id_shared_by_idx" ON "file_share" USING btree ("file_id","shared_by");--> statement-breakpoint
CREATE INDEX "file_share_expires_at_idx" ON "file_share" USING btree ("expires_at");--> statement-breakpoint
CREATE INDEX "file_share_is_public_idx" ON "file_share" USING btree ("is_public");--> statement-breakpoint
CREATE INDEX "file_share_is_public_expires_at_idx" ON "file_share" USING btree ("is_public","expires_at");--> statement-breakpoint
CREATE INDEX "file_share_recipient_share_id_idx" ON "file_share_recipient" USING btree ("share_id");--> statement-breakpoint
CREATE INDEX "file_share_recipient_email_idx" ON "file_share_recipient" USING btree ("email");--> statement-breakpoint
CREATE INDEX "file_share_recipient_share_id_email_idx" ON "file_share_recipient" USING btree ("share_id","email");--> statement-breakpoint
CREATE INDEX "folder_owner_id_idx" ON "folder" USING btree ("owner_id");--> statement-breakpoint
CREATE INDEX "folder_parent_id_idx" ON "folder" USING btree ("parent_id");--> statement-breakpoint
CREATE INDEX "folder_owner_id_parent_id_idx" ON "folder" USING btree ("owner_id","parent_id");--> statement-breakpoint
CREATE INDEX "folder_owner_id_name_idx" ON "folder" USING btree ("owner_id","name");--> statement-breakpoint
CREATE INDEX "folder_name_idx" ON "folder" USING btree ("name");--> statement-breakpoint
CREATE INDEX "folder_share_folder_id_idx" ON "folder_share" USING btree ("folder_id");--> statement-breakpoint
CREATE INDEX "folder_share_shared_by_idx" ON "folder_share" USING btree ("shared_by");--> statement-breakpoint
CREATE INDEX "folder_share_folder_id_shared_by_idx" ON "folder_share" USING btree ("folder_id","shared_by");--> statement-breakpoint
CREATE INDEX "folder_share_expires_at_idx" ON "folder_share" USING btree ("expires_at");--> statement-breakpoint
CREATE INDEX "folder_share_is_public_idx" ON "folder_share" USING btree ("is_public");--> statement-breakpoint
CREATE INDEX "folder_share_is_public_expires_at_idx" ON "folder_share" USING btree ("is_public","expires_at");--> statement-breakpoint
CREATE INDEX "folder_share_recipient_share_id_idx" ON "folder_share_recipient" USING btree ("share_id");--> statement-breakpoint
CREATE INDEX "folder_share_recipient_email_idx" ON "folder_share_recipient" USING btree ("email");--> statement-breakpoint
CREATE INDEX "folder_share_recipient_share_id_email_idx" ON "folder_share_recipient" USING btree ("share_id","email");--> statement-breakpoint
CREATE INDEX "session_user_id_idx" ON "session" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "session_expires_at_idx" ON "session" USING btree ("expires_at");--> statement-breakpoint
CREATE INDEX "trashed_item_owner_id_idx" ON "trashed_item" USING btree ("owner_id");--> statement-breakpoint
CREATE INDEX "trashed_item_item_id_idx" ON "trashed_item" USING btree ("item_id");--> statement-breakpoint
CREATE INDEX "trashed_item_owner_id_item_id_idx" ON "trashed_item" USING btree ("owner_id","item_id");--> statement-breakpoint
CREATE INDEX "trashed_item_trashed_at_idx" ON "trashed_item" USING btree ("trashed_at");